# Generated by Django 4.0.2 on 2022-02-14 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tehtavat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tehtava',
            name='kategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tehtavat.kategoria'),
        ),
    ]
